<?php

namespace AppBundle\Repository;

/**
 * arbeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArbeRepository extends \Doctrine\ORM\EntityRepository
{
}
